"use client";
import {useEffect,useRef,useState} from "react";
const PAGE_COUNT=15,GAME_URL="https://phil-casey-flight-adventure.rinercomconstruct.chatgpt.site/";
type Student={id:number;name:string;email:string};
const GameHotspot=()=> <a className="game-hotspot" href={GAME_URL} target="_blank" rel="noreferrer" aria-label="Start Phil and Casey: Flight Adventure" title="Start the journey"/>;
export default function PresentSimpleWorkbook({teacherPreview=false}:{teacherPreview?:boolean}){
 const [student,setStudent]=useState<Student|null>(null),[page,setPage]=useState(1),[imageUrl,setImageUrl]=useState(""),[scrollUrls,setScrollUrls]=useState<string[]>([]),[scrollMode,setScrollMode]=useState(true),[complete,setComplete]=useState(false),[message,setMessage]=useState("Checking access…"),[loading,setLoading]=useState(true);const code=useRef<string|undefined>();
 useEffect(()=>{if(!teacherPreview){const session=JSON.parse(localStorage.getItem("librimania-session")||"null");if(!session?.code||session.role!=="student"){setMessage("This workbook is available only to enrolled students. Log in from the main site first.");setLoading(false);return}code.current=session.code}fetch("/api/student/workbook",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"reader-access",code:code.current})}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);setStudent(d.student);setMessage("")}).catch(e=>setMessage(e.message)).finally(()=>setLoading(false))},[teacherPreview]);
 useEffect(()=>{if(!student||complete||scrollMode)return;let cancelled=false,currentUrl="";setLoading(true);fetch("/api/student/workbook-page",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({code:code.current,page})}).then(async r=>{if(!r.ok){const d=await r.json();throw new Error(d.error)}return r.blob()}).then(blob=>{if(cancelled)return;currentUrl=URL.createObjectURL(blob);setImageUrl(old=>{if(old)URL.revokeObjectURL(old);return currentUrl});setMessage("")}).catch(e=>setMessage(e.message)).finally(()=>{if(!cancelled)setLoading(false)});return()=>{cancelled=true;if(currentUrl)URL.revokeObjectURL(currentUrl)}},[student,page,complete,scrollMode]);
 useEffect(()=>{if(!student||!scrollMode||scrollUrls.length)return;let cancelled=false;setLoading(true);Promise.all(Array.from({length:PAGE_COUNT},(_,i)=>fetch("/api/student/workbook-page",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({code:code.current,page:i+1})}).then(async r=>{if(!r.ok){const d=await r.json();throw new Error(d.error)}return r.blob()}))).then(blobs=>{if(cancelled)return;setScrollUrls(blobs.map(blob=>URL.createObjectURL(blob)));setMessage("")}).catch(e=>setMessage(e.message)).finally(()=>{if(!cancelled)setLoading(false)});return()=>{cancelled=true}},[student,scrollMode,scrollUrls.length]);
 useEffect(()=>()=>{scrollUrls.forEach(url=>URL.revokeObjectURL(url))},[scrollUrls]);
 function previous(){if(complete){setComplete(false);setPage(PAGE_COUNT)}else setPage(v=>Math.max(1,v-1))}function next(){if(page===PAGE_COUNT)setComplete(true);else setPage(v=>Math.min(PAGE_COUNT,v+1))}
 useEffect(()=>{const keys=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&["p","s"].includes(e.key.toLowerCase())){e.preventDefault();return}if(e.key==="ArrowLeft")previous();if(e.key==="ArrowRight")next()};window.addEventListener("keydown",keys);return()=>window.removeEventListener("keydown",keys)});
 if(!student)return <main className="reader-gate"><div><p>STUDENT ACCESS</p><h1>Present Simple: Travel Edition</h1><p>{message}</p><a href="/">Return to Librimania</a></div></main>;
 return <main className="reader-shell" onContextMenu={e=>e.preventDefault()}><header className="reader-header"><a href={teacherPreview?"/teacher":"/librimania_student_dashboard_prototype.html"}>{teacherPreview?"← Teacher’s mode":"← My dashboard"}</a><div><span>Present Simple · Travel workbook</span><strong>{student.name}</strong></div></header>{complete?<section className="reader-complete"><p>WORKBOOK COMPLETE</p><h1>Ready to practise?</h1><p>First study the workbook and complete the written exercises. Then play <strong>Phil &amp; Casey: Flight Adventure</strong> to reinforce the same grammar in a lighter, gamified format.</p><a href={GAME_URL} target="_blank" rel="noreferrer">Play the game</a><button onClick={()=>{setComplete(false);setPage(1)}}>Read the workbook again</button></section>:<section className="reader-viewer" aria-label="Protected workbook reader"><div className="reader-controls"><span>View only · assigned student material</span><div><button className={scrollMode?"active":""} onClick={()=>setScrollMode(true)}>↕ Scroll pages</button><button className={!scrollMode?"active":""} onClick={()=>setScrollMode(false)}>▤ One page</button></div></div>{scrollMode?<div className="reader-scroll">{loading&&<div className="reader-scroll-loading">Loading all pages…</div>}{message&&<div className="reader-error">{message}</div>}{scrollUrls.map((url,i)=><figure key={url}><figcaption>Page {i+1} / {PAGE_COUNT}</figcaption><img src={url} alt={`Present Simple Travel workbook page ${i+1}`} draggable={false}/>{i===12&&<GameHotspot/>}</figure>)}</div>:<><div className="reader-meta"><span>Page {page} / {PAGE_COUNT}</span><span>Use arrow keys or the buttons below</span></div><div className="reader-page">{loading&&<div className="reader-loading">Loading page…</div>}{message&&<div className="reader-error">{message}</div>}{imageUrl&&<img src={imageUrl} alt={`Present Simple Travel workbook page ${page}`} draggable={false}/>} {page===13&&<GameHotspot/>}</div><nav><button onClick={previous} disabled={page===1}>← Previous</button><div>{Array.from({length:PAGE_COUNT},(_,i)=><button key={i} className={page===i+1?"active":""} aria-label={`Page ${i+1}`} onClick={()=>setPage(i+1)}>{i+1}</button>)}</div><button onClick={next}>{page===PAGE_COUNT?"Finish":"Next →"}</button></nav></>}<footer><span>Study first, practise afterwards.</span><a href={GAME_URL} target="_blank" rel="noreferrer">Play Phil &amp; Casey: Flight Adventure →</a></footer></section>}</main>
}
